flowchart LR
  sweet["sweet girls<br/>(1994-1998)<br/>門田匡陽: Vocals/Bass<br/>内田武瑠: Drums<br/>&lt;友人A&gt;: Guitar"]
  sunchester["サンチェスター・ユナイテッドFC<br/>(1998-1999)<br/>門田匡陽: Vocals/Guitar<br/>内田武瑠: Vocals/Guitar<br/>丸山潤: Vocals/Guitar<br/>伊藤大地: Drums"]
  burger1["BURGER NUDS<br/>(1999-2004)<br/>門田匡陽: Vocal/Guitar<br/>内田武瑠: Drums/Vocals<br/>丸山潤: Bass/Vocals"]
  gdhm2004["Good Dog Happy Men<br/>(2004 ...)<br/>門田匡陽: Vocal/Guitar<br/>内田武瑠: Drums/Percussions/Vocals<br/>伊藤大地: Drums/Percussions/Vocals<br/>韮沢雄希: Bass/Vocals<br/>城所祐一: Guitar/Vocals"]
  gdhm0506["Good Dog Happy Men<br/>(2005-2006 ...)<br/>門田匡陽: Vocal/Guitar<br/>内田武瑠: Drums/Percussions/Vocals<br/>伊藤大地: Drums/Percussions/Vocals<br/>韮沢雄希: Bass/Vocals"]
  gdhm0709["Good Dog Happy Men<br/>(2007-2009 ...)<br/>門田匡陽: Vocal/Guitar<br/>内田武瑠: Drums/Percussions/Vocals<br/>伊藤大地: Drums/Percussions/Vocals<br/>韮沢雄希: Bass/Vocals"]
  gdhm0910["Good Dog Happy Men<br/>(2009-2010 ...)<br/>門田匡陽: Vocal/Guitar<br/>内田武瑠: Drums/Percussions/Vocals"]
  hisband["門田匡陽 -His Band-<br/>(2010-2011)<br/>門田匡陽: Vocal/Guitar<br/>河相巧矢: Guitar/Vocals<br/>水野雅昭: Drums<br/>菅原将之: Bass/Vocals<br/>金戸覚: Bass<br/>高野勲: Keyboards"]
  calm["門田匡陽 with CalmCalm<br/>(2012)<br/>門田匡陽: Vocal/Guitar<br/>水野雅昭: Drums<br/>maryne: Bass"]
  iwsgb["I Will Say Good Bye<br/>(2012)<br/>門田匡陽: Vocal/Guitar<br/>水野雅昭: Drums/Pad/Guitar"]
  ptm["Poet-type.M<br/>(2013-2023 ...)<br/>門田匡陽: Vocal/Guitar/Manip<br/>水野雅昭: Drums<br/>河相巧矢: Guitar<br/>宇野剛史: Bass<br/>伊藤大地: Drums<br/>伊賀航: Bass<br/>Nao Yanagawa: Keyboards<br/>kalminrot: Cho/Manip/Guitar<br/>楢原英介: Guitar/Violin/Keyboards"]
  mondenSolo["門田匡陽 (solo)<br/>(2023-)<br/>門田匡陽: Vocal/Guitar"]

  curly["Curly Hair<br/>(2005-)<br/>前田太一: Guitar"]
  spank["SPANK PAGE<br/>(2006-2012 ...)<br/>仲手川裕介: Vocals/Guitar/Key<br/>水野雅昭: Drums"]
  cherrys["Cherry's<br/>(2004-)<br/>伊藤大地: Vocals/Drums/Whistle"]
  burger2["BURGER NUDS<br/>(2014-)<br/>門田匡陽: Vocal/Guitar<br/>内田武瑠: Drums/Vocals<br/>丸山潤: Bass/Vocals"]
  chopin1["ショピン<br/>(2009-2011 ...)<br/>野々歩: Vocals<br/>タカハシペチカ: Guitar<br/>田中馨: Bass"]
  chopin2["ショピン<br/>(2011-)<br/>野々歩: Vocals<br/>タカハシペチカ: Guitar<br/>田中馨: Guitar<br/>野村卓史: Keyboards"]
  sakerock1["SAKEROCK<br/>(2000-2002 ...)<br/>伊藤大地: Drums/Percussions<br/>田中馨: Bass<br/>星野源: Guitar/Marimba<br/>浜野謙太: Trombone/Scat"]
  sakerock2["SAKEROCK<br/>(2002-2015)<br/>伊藤大地: Drums/Percussions<br/>田中馨: Bass<br/>星野源: Guitar/Marimba<br/>浜野謙太: Trombone/Scat<br/>野村卓史: Keyboards"]
  ghlw["グッドラックヘイワ<br/>(2004-)<br/>伊藤大地: Drums/Whistle<br/>野村卓史: Keyboards"]
  hosono["星野源 (solo)<br/>(2010-)<br/>星野源: Vocals/Guitar"]
  hinemos["ヒネモス<br/>(2010-) [2004 結成]<br/>タカハシペチカ: Guitar"]
  vola["VOLA & THE ORIENTAL MACHINE<br/>(2008-2012 ...)<br/>アヒト・イナザワ: Vocals/Guitar/Drums<br/>中畑大樹: Drums<br/>楢原英介: Guitar<br/>有江嘉典: Bass"]
  zainichi["在日ファンク<br/>(2007-)<br/>浜野謙太: Vocals"]
  sentiline["センチライン<br/>(2001-2008)<br/>枝松直紀: Guitar/Vocals<br/>河相巧矢: Guitar<br/>尾崎宏明: Bass<br/>堀内啓史: Drums"]
  archaic["アルカイックスマイル・オブ・エリナ<br/>(2009)<br/>枝松直紀: Guitar/Vocals<br/>菅原将之: Bass<br/>平沼正人: Drums"]
  mikito["みきとP<br/>(2009-)<br/>みきとP: Write/Arrange/Mix"]

  sweet -->|member| sunchester
  sunchester -->|member| burger1
  sunchester -->|member| sakerock1
  burger1 -->|member| gdhm2004
  burger1 -->|member| burger2
  gdhm2004 -->|member| gdhm0506
  gdhm0506 -->|member| gdhm0709
  gdhm0506 -.->|support: 前田太一| curly
  gdhm0709 -->|member| gdhm0910
  gdhm0709 -.->|support| ptm
  gdhm0910 -->|member/support| hisband
  gdhm0910 -.->|support| chopin1
  hisband -->|member/support| calm
  calm -->|member/support| iwsgb
  calm -.->|support| mondenSolo
  iwsgb -->|member/support| ptm
  iwsgb -->|member| burger2
  ptm -->|member/support| mondenSolo

  spank -.->|support: 水野雅昭| hisband
  sentiline -->|member| archaic
  sentiline -.->|support: 河相巧矢| gdhm0910
  archaic -->|member| mikito
  archaic -.->|support: 菅原将之| gdhm0910

  sakerock1 -->|member| sakerock2
  sakerock1 -->|member| ghlw
  sakerock1 -.->|support| hosono
  sakerock2 -->|member| cherrys
  sakerock2 -->|member| chopin1
  sakerock2 -->|member| ghlw
  sakerock2 -->|member| zainichi
  sakerock2 -.->|support| hosono

  chopin1 -->|member| chopin2
  chopin1 -->|member| hinemos
  chopin2 -->|member| burger2
  chopin2 -.->|support| ptm

  vola -.->|support: 楢原英介 / 中畑大樹| ptm
