flowchart LR
  sweet["sweet girls<br/>(1994-1998)"]
  sunchester["サンチェスター・ユナイテッドFC<br/>(1998-1999)"]
  burger1["BURGER NUDS<br/>(1999-2004)"]
  gdhm2004["Good Dog Happy Men<br/>(2004 ...)"]
  gdhm0506["Good Dog Happy Men<br/>(2005-2006 ...)"]
  gdhm0709["Good Dog Happy Men<br/>(2007-2009 ...)"]
  gdhm0910["Good Dog Happy Men<br/>(2009-2010 ...)"]
  hisband["門田匡陽 -His Band-<br/>(2010-2011)"]
  calm["門田匡陽 with CalmCalm<br/>(2012)"]
  iwsgb["I Will Say Good Bye<br/>(2012)"]
  ptm["Poet-type.M<br/>(2013-2023 ...)"]
  mondenSolo["門田匡陽 (solo)<br/>(2023-)"]

  curly["Curly Hair<br/>(2005-)"]
  spank["SPANK PAGE<br/>(2006-2012 ...)"]
  cherrys["Cherry's<br/>(2004-)"]
  burger2["BURGER NUDS<br/>(2014-)"]
  chopin1["ショピン<br/>(2009-2011 ...)"]
  chopin2["ショピン<br/>(2011-)"]
  sakerock1["SAKEROCK<br/>(2000-2002 ...)"]
  sakerock2["SAKEROCK<br/>(2002-2015)"]
  ghlw["グッドラックヘイワ<br/>(2004-)"]
  hosono["星野源 (solo)<br/>(2010-)"]
  hinemos["ヒネモス<br/>(2010-) [2004 結成]"]
  vola["VOLA & THE ORIENTAL MACHINE<br/>(2008-2012 ...)"]
  zainichi["在日ファンク<br/>(2007-)"]
  sentiline["センチライン<br/>(2001-2008)"]
  archaic["アルカイックスマイル・オブ・エリナ<br/>(2009)"]
  mikito["みきとP<br/>(2009-)"]

  sweet -->|門田匡陽<br/>内田武瑠| sunchester
  sunchester -->|門田匡陽<br/>内田武瑠<br/>丸山潤| burger1
  sunchester -->|伊藤大地| sakerock1
  burger1 -->|門田匡陽<br/>内田武瑠| gdhm2004
  burger1 -->|門田匡陽<br/>内田武瑠<br/>丸山潤| burger2
  gdhm2004 -->|門田匡陽<br/>内田武瑠<br/>伊藤大地<br/>韮沢雄希| gdhm0506
  gdhm0506 -->|門田匡陽<br/>内田武瑠<br/>伊藤大地<br/>韮沢雄希| gdhm0709
  gdhm0506 -.->|support: 前田太一| curly
  gdhm0709 -->|門田匡陽<br/>内田武瑠| gdhm0910
  gdhm0709 -.->|support: 門田匡陽 / 伊藤大地| ptm
  gdhm0910 -->|門田匡陽| hisband
  gdhm0910 -.->|support: 伊藤大地| chopin1
  hisband -->|門田匡陽<br/>水野雅昭| calm
  calm -->|門田匡陽<br/>水野雅昭| iwsgb
  calm -.->|門田匡陽| mondenSolo
  iwsgb -->|門田匡陽<br/>水野雅昭| ptm
  iwsgb -->|門田匡陽| burger2
  ptm -->|門田匡陽| mondenSolo

  spank -.->|水野雅昭| hisband
  sentiline -->|枝松直紀| archaic
  sentiline -.->|河相巧矢| gdhm0910
  archaic -->|菅原将之| mikito
  archaic -.->|菅原将之| gdhm0910

  sakerock1 -->|伊藤大地<br/>田中馨<br/>星野源<br/>浜野謙太| sakerock2
  sakerock1 -->|伊藤大地| ghlw
  sakerock1 -.->|星野源| hosono
  sakerock2 -->|伊藤大地| cherrys
  sakerock2 -->|田中馨| chopin1
  sakerock2 -->|伊藤大地<br/>野村卓史| ghlw
  sakerock2 -->|浜野謙太| zainichi
  sakerock2 -.->|星野源| hosono

  chopin1 -->|野々歩<br/>タカハシペチカ<br/>田中馨| chopin2
  chopin1 -->|タカハシペチカ| hinemos
  chopin2 -->|田中馨| burger2
  chopin2 -.->|support: 野村卓史| ptm

  vola -.->|support: 楢原英介 / 中畑大樹| ptm
